config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from klimaat_helpdesk.qa.views import new_question

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("", include("klimaat_helpdesk.qa.urls", namespace='questions')),
    path("moderation/", include("klimaat_helpdesk.moderation.urls", namespace="moderation")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("klimaat_helpdesk.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

klimaat_helpdesk/moderation/urls.py
from django.urls import path

from klimaat_helpdesk.moderation.views import new_questions_list, approve_question, assign_handler, question_handling, \
    reject_question, assign_expert, create_expert, create_expert_profile

app_name = "moderation"


urlpatterns = [
    path('', new_questions_list, name='new-questions'),
    path('approve/<int:pk>', approve_question, name='approve'),
    path('reject/<int:pk>', reject_question, name='reject'),
    path('assign-handler/<int:pk>', assign_handler, name='assign-handler'),
    path('handling', question_handling, name='handling'),
    path('assign-expert/<int:pk>', assign_expert, name='assign-expert'),
    path('create-expert', create_expert, name='create-expert'),
    path('create-expert-profile/<int:pk>', create_expert_profile, name='create-expert-profile'),
]

klimaat_helpdesk/qa/urls.py
from django.urls import path
from django.views.generic import TemplateView

from klimaat_helpdesk.qa.views import new_question, editor_home, assign_handler, assign_reviewer, assign_expert, \
    create_answer, review_answer, handler_home, question_details, home_page

app_name = "questions"


urlpatterns = [
    path('', view=home_page, name='home'),
    path('ask', new_question, name='ask'),
    path('ask/thanks', TemplateView.as_view(template_name='qa/new_question_thanks.html'), name='new-question-thanks'),
    path('question', TemplateView.as_view(template_name='question.html'), name='question'),
    path('experts', TemplateView.as_view(template_name='experts.html'), name='experts'),

    path('become-expert', TemplateView.as_view(template_name='become.html'), name='become-expert'),
    path('expert', TemplateView.as_view(template_name='expert_profile.html'), name='expert'),
    path('editor/', view=editor_home, name='editor-home'),
    path('handler/', view=handler_home, name='handler-home'),
    path('question/<int:pk>', view=question_details, name='question-details'),
    path('<int:pk>/assign-handler/', view=assign_handler, name='assign-handler'),
    path('<int:pk>/assign-reviewer/', view=assign_reviewer, name='assign-reviewer'),
    path('<int:pk>/assign-expert', view=assign_expert, name='assign-expert'),
    path('answer/<int:pk>/create', view=create_answer, name='create-answer'),
    path('review/<int:pk>/create', view=review_answer, name='create-review')
]

klimaat_helpdesk/users/urls.py
from django.urls import path

from klimaat_helpdesk.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
    create_user)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("create/", view=create_user, name="create-user"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

klimaat_helpdesk/moderation/forms.py
from django.contrib.auth import get_user_model, forms as auth_forms
from django.core.exceptions import ValidationError
from django import forms
from django.utils.translation import ugettext_lazy as _

from klimaat_helpdesk.users import EXPERT
from klimaat_helpdesk.users.models import ExpertProfile

User = get_user_model()


class ExpertCreationForm(forms.Form):
    name = forms.CharField(max_length=255, label=_('name'), required=True)
    email = forms.EmailField(label=_('email'), required=True)

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if User.objects.filter(email=email).exists():
            raise ValidationError(_('That e-mail is already on our database'))
        return email

    def save(self, commit=True):
        user = User.objects.create(
            name=self.cleaned_data['name'],
            username=self.cleaned_data['email'],
            email=self.cleaned_data['email'],
            role=EXPERT,
        )
        ExpertProfile.objects.create(
            user=user
        )
        return user

klimaat_helpdesk/moderation/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied, ValidationError
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.timezone import now
from django.views.generic import ListView, UpdateView, CreateView, FormView
from django.views.generic.base import View
from django.utils.translation import gettext as _

from klimaat_helpdesk.moderation.forms import ExpertCreationForm
from klimaat_helpdesk.qa import ANSWERING
from klimaat_helpdesk.qa.models import TemporaryQuestion, Question
from klimaat_helpdesk.users import HANDLER, EXPERT
from klimaat_helpdesk.users.models import ExpertProfile

User = get_user_model()


class NewQuestions(LoginRequiredMixin, ListView):
    """List of questions in need of a decision. Either approve or reject.
    """
    model = TemporaryQuestion
    context_object_name = 'questions'
    template_name = 'moderation/new_questions.html'

    def get_queryset(self):
        qs = super(NewQuestions, self).get_queryset()
        return qs.filter(approved=None)


new_questions_list = NewQuestions.as_view()


class ApproveQuestion(LoginRequiredMixin, View):
    """A bit more convoluted than needed. To keep the principle that only a post request can be used to update/create an
    object."""
    model = TemporaryQuestion
    context_object_name = 'question'
    template_name = 'moderation/approve_question.html'

    def get(self, request, **kwargs):
        question = get_object_or_404(self.model, pk=kwargs['pk'])
        return render(self.request, self.template_name, {self.context_object_name: question})

    def post(self, request, **kwargs):
        temp_question = get_object_or_404(self.model, pk=kwargs['pk'])
        question = temp_question.approve(self.request.user)
        return redirect(reverse_lazy('moderation:assign-handler', kwargs={'pk': question.pk}))


approve_question = ApproveQuestion.as_view()


class RejectQuestion(LoginRequiredMixin, UpdateView):
    """When rejecting a question, a reason must be provided. This is useful for bookkeeping and to inform the user who
    asked."""

    model = TemporaryQuestion
    context_object_name = 'question'
    template_name = 'moderation/reject_question.html'
    fields = ['rejection', ]
    success_url = reverse_lazy('moderation:new-questions')

    def form_valid(self, form):
        self.object.reject()
        return super(RejectQuestion, self).form_valid(form)


reject_question = RejectQuestion.as_view()


class QuestionAssignHandler(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['handler', ]
    template_name = 'moderation/assign_handler.html'
    success_url = reverse_lazy('moderation:new-questions')
    context_object_name = 'question'

    def get_form(self, *args, **kwargs):
        form = super(QuestionAssignHandler, self).get_form(*args, **kwargs)
        form.fields['handler'].queryset = User.objects.filter(role__gte=HANDLER)
        return form

    def form_valid(self, form):
        self.object.date_assigned_handler = now()
        self.object.save()
        return super(QuestionAssignHandler, self).form_valid(form)


assign_handler = QuestionAssignHandler.as_view()


class QuestionHandling(LoginRequiredMixin, ListView):
    """List the questions the logged-in user has to handle.
    """
    model = Question
    context_object_name = 'questions'
    template_name = 'moderation/handling.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(handler=self.request.user)


question_handling = QuestionHandling.as_view()


class AssignExpert(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Question
    fields = ['expert', ]
    context_object_name = 'question'
    template_name = 'moderation/assign_expert.html'
    success_message = "Expert added successfully"

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().handler != self.request.user:
            return HttpResponseForbidden()
        return super(AssignExpert, self).dispatch(request, *args, **kwargs)

    def get_form(self, *args, **kwargs):
        form = super(AssignExpert, self).get_form(*args, **kwargs)
        form.fields['expert'].queryset = User.objects.filter(role__gte=EXPERT)
        return form

    def get_success_url(self):
        return reverse_lazy('moderation:assign-expert', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object.date_assigned_expert = now()
        self.object.status = ANSWERING
        self.object.save()
        return super(AssignExpert, self).form_valid(form)


assign_expert = AssignExpert.as_view()


class CreateExpert(LoginRequiredMixin, SuccessMessageMixin, FormView):
    form_class = ExpertCreationForm
    template_name = 'moderation/create_expert.html'
    extra_context = {'title': _('Update Expert Profile')}
    success_message = _('Expert created successfully')

    def form_valid(self, form):
        self.object = form.save()
        return super(CreateExpert, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('moderation:create-expert-profile', kwargs={'pk': self.object.expert_profile.pk})


create_expert = CreateExpert.as_view()


class CreateExpertProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ExpertProfile
    fields = ['bio',
              'profile_picture',
              'areas_expertise',
              'affiliation',
              'website',
              'twitter_profile',
              'linkedin_profile',
              ]
    template_name = 'moderation/create_expert_profile.html'
    success_message = _('Expert profile created successfully')
    success_url = reverse_lazy('moderation:handling')
    context_object_name = 'profile'


create_expert_profile = CreateExpertProfile.as_view()

klimaat_helpdesk/qa/views.py
from logging import getLogger

from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse
from django.utils.timezone import now

from django.views.generic import FormView, ListView, UpdateView, DetailView
from django.views.generic.base import View, TemplateView

from klimaat_helpdesk.qa.forms import AddNewQuestion, AskQuestion
from klimaat_helpdesk.qa.models import Question, Answer, Review, Category, TemporaryQuestion
from klimaat_helpdesk.users import HANDLER, EXPERT, REVIEWER

User = get_user_model()

logger = getLogger(__name__)


class HomePage(TemplateView):
    template_name = 'qa/home_page.html'

    def get_context_data(self, **kwargs):
        latest_questions = Question.objects.more_recent(10)
        categories = Category.objects.all()
        expert_profile = None
        context = super(HomePage, self).get_context_data(**kwargs)
        context.update({
            'latest_questions': latest_questions,
            'categories': categories,
            'expert_profile': expert_profile,
        })
        return context

home_page = HomePage.as_view()


class NewQuestion(FormView):
    form_class = AskQuestion
    template_name = 'qa/new_question.html'
    success_url = reverse_lazy('questions:new-question-thanks')

    def form_valid(self, form):
        TemporaryQuestion.objects.create(
            question=form.cleaned_data['question'],
            asked_by=form.cleaned_data.get('asked_by', None),
            asked_by_ip=self.request.META.get('REMOTE_ADDR')
        )
        return super(NewQuestion, self).form_valid(form)


new_question = NewQuestion.as_view()


class EditorHomeView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'qa/editor_home.html'


editor_home = EditorHomeView.as_view()


class HandlerHomeView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'qa/handler_home.html'


handler_home = HandlerHomeView.as_view()


class AssignHandlerView(UpdateView):
    model = Question
    fields = ['handler', ]
    template_name = 'qa/assign_handler.html'
    success_url = reverse_lazy('questions:editor-home')
    context_object_name = 'question'

    def get_form(self, *args, **kwargs):
        form = super(AssignHandlerView, self).get_form(*args, **kwargs)
        form.fields['handler'].queryset = User.objects.filter(role__gte=HANDLER)
        return form

    def form_valid(self, form):
        self.object.date_assigned_handler = now()
        self.object.save()
        return super(AssignHandlerView, self).form_valid(form)


assign_handler = AssignHandlerView.as_view()


class AssignExpert(UpdateView):
    model = Question
    fields = ['expert', ]
    template_name = 'qa/assign_expert.html'
    success_url = reverse_lazy('questions:handler-home')

    def get_form(self, *args, **kwargs):
        form = super(AssignExpert, self).get_form(*args, **kwargs)
        form.fields['expert'].queryset = User.objects.filter(role__gte=EXPERT)
        return form

    def form_valid(self, form):
        self.object.date_assigned_expert = now()
        self.object.save()
        Answer.objects.create(
            question=self.object,
            author=form.cleaned_data['expert']
        )

        return super(AssignExpert, self).form_valid(form)


assign_expert = AssignExpert.as_view()


class AssignReviewer(UpdateView):
    model = Question
    fields = ['reviewer', ]
    template_name = 'qa/assign_reviewer.html'
    success_url = reverse_lazy('questions:handler-home')

    def get_form(self, *args, **kwargs):
        form = super(AssignReviewer, self).get_form(*args, **kwargs)
        form.fields['reviewer'].queryset = User.objects.filter(role__gte=REVIEWER)
        return form

    def form_valid(self, form):
        self.object.date_assigned_reviewer = now()
        self.object.save()
        Review.objects.create(
            question=self.object,
            reviewer=form.cleaned_data['reviewer']
        )

        return super(AssignReviewer, self).form_valid(form)


assign_reviewer = AssignReviewer.as_view()


class CreateAnswer(UpdateView):
    model = Answer
    fields = ['answer', ]
    context_object_name = 'answer'
    template_name = 'qa/create_answer.html'
    success_url = '/'

    def form_valid(self, form):
        self.object.date_submitted = now()
        self.object.save()
        return super(CreateAnswer, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('questions:question-details', args=[self.object.question.pk])


create_answer = CreateAnswer.as_view()


class ReviewAnswer(UpdateView):
    model = Review
    fields = ['remarks', ]
    context_object_name = 'review'
    template_name = 'qa/create_review.html'
    success_url = '/'

    def form_valid(self, form):
        self.object.date_submitted = now()
        self.object.save()
        return super(ReviewAnswer, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('questions:question-details', args=[self.object.question.pk])


review_answer = ReviewAnswer.as_view()


class QuestionDetails(DetailView):
    model = Question
    template_name = 'qa/question_details.html'
    context_object_name = 'question'


question_details = QuestionDetails.as_view()

klimaat_helpdesk/templates/ask.html
{% extends 'base.html' %}
{% load i18n static %}
{% block content %}
  <section class="hero is-primary is-bold">
    <div class="hero-body">
      <div class="container">
        <h2 class="title is-size-2-desktop is-size-3-touch">Helpdesk Klimaat</h2>
        <h3 class="subtitle is-size-4-desktop is-size-5-touch">{% blocktrans %}All the questions you may have
          regarding climate breakdown, global warming, answered by experts.{% endblocktrans %}</h3>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="container">
      <section class="section question-intro">
        <div class="title">Ask your question</div>
        <div><p>After you ask your question, we will review it and assign it to an expert to answer it. The entire
          process
          may take up to a couple of weeks. If you would like to be informed about the progress, you can leave us your
          e-mail.</p>
        </div>
      </section>
      <section class="section question-form">
        <div class="columns">
          <div class="column is-half is-offset-one-quarter">
            <form class="form boxed">
              <div class="field">
                <label class="label">Email (optional)</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" type="email" placeholder="Email input"/>
                  <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
                <p class="help">Only if you want to receive updates about your question</p>
              </div>
              <div class="field">
                <label class="label">Message</label>
                <div class="control">
                  <textarea class="textarea" placeholder="Textarea"></textarea>
                </div>
              </div>
              <div class="field">
                <div class="control">
                  <label class="checkbox">
                    <input type="checkbox">
                    I agree to the <a href="#">terms and conditions</a>
                  </label>
                </div>
              </div>
              <div class="field">
                <div class="control">
                  <button class="button is-link">Submit Question</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </section>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/base_old.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Klimaat Helpdesk{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


  {% endblock %}

</head>

<body>

<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'questions:home' %}">Klimaat Helpdesk</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'questions:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'questions:editor-home' %}">Editor Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'questions:handler-home' %}">Handler Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'questions:editor-home' %}"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}

  <!-- Bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
          integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
</body>
</html>

klimaat_helpdesk/templates/experts.html
{% extends 'base.html' %}
{% load static i18n %}
{% block content %}
  <section class="hero is-primary is-bold">
    <div class="hero-body">
      <div class="container">
        <h2 class="title is-size-2-desktop is-size-3-touch">Helpdesk Klimaat</h2>
        <h3 class="subtitle is-size-4-desktop is-size-5-touch">{% blocktrans %}All the questions you may have
          regarding climate breakdown, global warming, answered by experts.{% endblocktrans %}</h3>
      </div>
    </div>
  </section>
  <main class="section">
    <div class="container">
      <header class="header">
        <div class="header-title"><h1 class="title">{% trans "Experts answering questions" %}</h1></div>
        <p class="subtitle is-4">These are all the experts answering questions on our website</p>
        <p>You can also <a href="{% url 'questions:become-expert' %}">become an expert</a></p>
      </header>
      <div class="section">
        <div class="boxed media">
          <div class="media-left">
            <figure class="image is-48x48"><img src="{% static 'images/portrait_placeholder.png' %}"
                                                alt="Profile Picture"/></figure>
          </div>
          <div class="media-content content">
            <div class="expert-title">
              <strong>Expert Number 1</strong>
              <time>Answering questions since 2019</time>
            </div>
            <div class="expert-bio">Sed sit amet massa tristique, vestibulum odio a, fermentum ex. Praesent iaculis
              finibus dui, vitae aliquam ligula maximus in. Praesent faucibus, tellus ornare vehicula eleifend, lacus
              est sollicitudin purus, sit amet lacinia lectus ipsum eget justo. Lorem ipsum dolor sit amet, consectetur
              adipiscing elit. Aenean tincidunt, urna a faucibus tristique, massa nibh varius sem, in sollicitudin justo
              urna varius nulla. Proin bibendum tincidunt magna id imperdiet. <a href="{% url 'questions:expert' %}">Read more...</a>
            </div>
          </div>
        </div>
        <div class="boxed media">
          <div class="media-left">
            <figure class="image is-48x48"><img src="{% static 'images/portrait_placeholder.png' %}"
                                                alt="Profile Picture"/></figure>
          </div>
          <div class="media-content content">
            <div class="expert-title">
              <strong>Expert Number 2</strong>
              <time>Answering questions since 2019</time>
            </div>
            <div class="expert-bio">Sed sit amet massa tristique, vestibulum odio a, fermentum ex. Praesent iaculis
              finibus dui, vitae aliquam ligula maximus in. Praesent faucibus, tellus ornare vehicula eleifend, lacus
              est sollicitudin purus, sit amet lacinia lectus ipsum eget justo. Lorem ipsum dolor sit amet, consectetur
              adipiscing elit. Aenean tincidunt, urna a faucibus tristique, massa nibh varius sem, in sollicitudin justo
              urna varius nulla. Proin bibendum tincidunt magna id imperdiet.
            </div>
          </div>
        </div>
        <div class="boxed media">
          <div class="media-left">
            <figure class="image is-48x48"><img src="{% static 'images/portrait_placeholder.png' %}"
                                                alt="Profile Picture"/></figure>
          </div>
          <div class="media-content content">
            <div class="expert-title">
              <strong>Expert Number 3</strong>
              <time>Answering questions since 2019</time>
            </div>
            <div class="expert-bio">Sed sit amet massa tristique, vestibulum odio a, fermentum ex. Praesent iaculis
              finibus dui, vitae aliquam ligula maximus in. Praesent faucibus, tellus ornare vehicula eleifend, lacus
              est sollicitudin purus, sit amet lacinia lectus ipsum eget justo. Lorem ipsum dolor sit amet, consectetur
              adipiscing elit. Aenean tincidunt, urna a faucibus tristique, massa nibh varius sem, in sollicitudin justo
              urna varius nulla. Proin bibendum tincidunt magna id imperdiet.
            </div>
          </div>
        </div>
        <div class="boxed media">
          <div class="media-left">
            <figure class="image is-48x48"><img src="{% static 'images/portrait_placeholder.png' %}"
                                                alt="Profile Picture"/></figure>
          </div>
          <div class="media-content content">
            <div class="expert-title">
              <strong>Expert Number 4</strong>
              <time>Answering questions since 2019</time>
            </div>
            <div class="expert-bio">Sed sit amet massa tristique, vestibulum odio a, fermentum ex. Praesent iaculis
              finibus dui, vitae aliquam ligula maximus in. Praesent faucibus, tellus ornare vehicula eleifend, lacus
              est sollicitudin purus, sit amet lacinia lectus ipsum eget justo. Lorem ipsum dolor sit amet, consectetur
              adipiscing elit. Aenean tincidunt, urna a faucibus tristique, massa nibh varius sem, in sollicitudin justo
              urna varius nulla. Proin bibendum tincidunt magna id imperdiet.
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}