config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from klimaat_helpdesk.qa.views import new_question

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("", include("klimaat_helpdesk.qa.urls", namespace='questions')),
    path("moderation/", include("klimaat_helpdesk.moderation.urls", namespace="moderation")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("klimaat_helpdesk.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

klimaat_helpdesk/moderation/urls.py
from django.urls import path

from klimaat_helpdesk.moderation.views import new_questions_list, approve_question, assign_handler, question_handling, \
    reject_question, assign_expert, create_expert, create_expert_profile

app_name = "moderation"


urlpatterns = [
    path('', new_questions_list, name='new-questions'),
    path('approve/<int:pk>', approve_question, name='approve'),
    path('reject/<int:pk>', reject_question, name='reject'),
    path('assign-handler/<int:pk>', assign_handler, name='assign-handler'),
    path('handling', question_handling, name='handling'),
    path('assign-expert/<int:pk>', assign_expert, name='assign-expert'),
    path('create-expert', create_expert, name='create-expert'),
    path('create-expert-profile/<int:pk>', create_expert_profile, name='create-expert-profile'),
]

klimaat_helpdesk/qa/urls.py
from django.urls import path
from django.views.generic import TemplateView

from klimaat_helpdesk.qa.views import new_question, editor_home, assign_handler, assign_reviewer, assign_expert, \
    create_answer, review_answer, handler_home, question_details, home_page

app_name = "questions"


urlpatterns = [
    path('', view=home_page, name='home'),
    path('ask', new_question, name='ask'),
    path('ask/thanks', TemplateView.as_view(template_name='qa/new_question_thanks.html'), name='new-question-thanks'),
    path('question', TemplateView.as_view(template_name='question.html'), name='question'),
    path('experts', TemplateView.as_view(template_name='experts.html'), name='experts'),

    path('become-expert', TemplateView.as_view(template_name='become.html'), name='become-expert'),
    path('expert', TemplateView.as_view(template_name='expert_profile.html'), name='expert'),
    path('editor/', view=editor_home, name='editor-home'),
    path('handler/', view=handler_home, name='handler-home'),
    path('question/<int:pk>', view=question_details, name='question-details'),
    path('<int:pk>/assign-handler/', view=assign_handler, name='assign-handler'),
    path('<int:pk>/assign-reviewer/', view=assign_reviewer, name='assign-reviewer'),
    path('<int:pk>/assign-expert', view=assign_expert, name='assign-expert'),
    path('answer/<int:pk>/create', view=create_answer, name='create-answer'),
    path('review/<int:pk>/create', view=review_answer, name='create-review')
]

klimaat_helpdesk/users/urls.py
from django.urls import path

from klimaat_helpdesk.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
    create_user)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("create/", view=create_user, name="create-user"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

klimaat_helpdesk/moderation/forms.py
from django.contrib.auth import get_user_model, forms as auth_forms
from django.core.exceptions import ValidationError
from django import forms
from django.utils.translation import ugettext_lazy as _

from klimaat_helpdesk.users import EXPERT
from klimaat_helpdesk.users.models import ExpertProfile

User = get_user_model()


class ExpertCreationForm(forms.Form):
    name = forms.CharField(max_length=255, label=_('name'), required=True)
    email = forms.EmailField(label=_('email'), required=True)

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if User.objects.filter(email=email).exists():
            raise ValidationError(_('That e-mail is already on our database'))
        return email

    def save(self, commit=True):
        user = User.objects.create(
            name=self.cleaned_data['name'],
            username=self.cleaned_data['email'],
            email=self.cleaned_data['email'],
            role=EXPERT,
        )
        ExpertProfile.objects.create(
            user=user
        )
        return user

klimaat_helpdesk/moderation/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied, ValidationError
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.timezone import now
from django.views.generic import ListView, UpdateView, CreateView, FormView
from django.views.generic.base import View
from django.utils.translation import gettext as _

from klimaat_helpdesk.moderation.forms import ExpertCreationForm
from klimaat_helpdesk.qa import ANSWERING
from klimaat_helpdesk.qa.models import TemporaryQuestion, Question
from klimaat_helpdesk.users import HANDLER, EXPERT
from klimaat_helpdesk.users.models import ExpertProfile

User = get_user_model()


class NewQuestions(LoginRequiredMixin, ListView):
    """List of questions in need of a decision. Either approve or reject.
    """
    model = TemporaryQuestion
    context_object_name = 'questions'
    template_name = 'moderation/new_questions.html'

    def get_queryset(self):
        qs = super(NewQuestions, self).get_queryset()
        return qs.filter(approved=None)


new_questions_list = NewQuestions.as_view()


class ApproveQuestion(LoginRequiredMixin, View):
    """A bit more convoluted than needed. To keep the principle that only a post request can be used to update/create an
    object."""
    model = TemporaryQuestion
    context_object_name = 'question'
    template_name = 'moderation/approve_question.html'

    def get(self, request, **kwargs):
        question = get_object_or_404(self.model, pk=kwargs['pk'])
        return render(self.request, self.template_name, {self.context_object_name: question})

    def post(self, request, **kwargs):
        temp_question = get_object_or_404(self.model, pk=kwargs['pk'])
        question = temp_question.approve(self.request.user)
        return redirect(reverse_lazy('moderation:assign-handler', kwargs={'pk': question.pk}))


approve_question = ApproveQuestion.as_view()


class RejectQuestion(LoginRequiredMixin, UpdateView):
    """When rejecting a question, a reason must be provided. This is useful for bookkeeping and to inform the user who
    asked."""

    model = TemporaryQuestion
    context_object_name = 'question'
    template_name = 'moderation/reject_question.html'
    fields = ['rejection', ]
    success_url = reverse_lazy('moderation:new-questions')

    def form_valid(self, form):
        self.object.reject()
        return super(RejectQuestion, self).form_valid(form)


reject_question = RejectQuestion.as_view()


class QuestionAssignHandler(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['handler', ]
    template_name = 'moderation/assign_handler.html'
    success_url = reverse_lazy('moderation:new-questions')
    context_object_name = 'question'

    def get_form(self, *args, **kwargs):
        form = super(QuestionAssignHandler, self).get_form(*args, **kwargs)
        form.fields['handler'].queryset = User.objects.filter(role__gte=HANDLER)
        return form

    def form_valid(self, form):
        self.object.date_assigned_handler = now()
        self.object.save()
        return super(QuestionAssignHandler, self).form_valid(form)


assign_handler = QuestionAssignHandler.as_view()


class QuestionHandling(LoginRequiredMixin, ListView):
    """List the questions the logged-in user has to handle.
    """
    model = Question
    context_object_name = 'questions'
    template_name = 'moderation/handling.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(handler=self.request.user)


question_handling = QuestionHandling.as_view()


class AssignExpert(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Question
    fields = ['expert', ]
    context_object_name = 'question'
    template_name = 'moderation/assign_expert.html'
    success_message = "Expert added successfully"

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().handler != self.request.user:
            return HttpResponseForbidden()
        return super(AssignExpert, self).dispatch(request, *args, **kwargs)

    def get_form(self, *args, **kwargs):
        form = super(AssignExpert, self).get_form(*args, **kwargs)
        form.fields['expert'].queryset = User.objects.filter(role__gte=EXPERT)
        return form

    def get_success_url(self):
        return reverse_lazy('moderation:assign-expert', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object.date_assigned_expert = now()
        self.object.status = ANSWERING
        self.object.save()
        return super(AssignExpert, self).form_valid(form)


assign_expert = AssignExpert.as_view()


class CreateExpert(LoginRequiredMixin, SuccessMessageMixin, FormView):
    form_class = ExpertCreationForm
    template_name = 'moderation/create_expert.html'
    extra_context = {'title': _('Update Expert Profile')}
    success_message = _('Expert created successfully')

    def form_valid(self, form):
        self.object = form.save()
        return super(CreateExpert, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('moderation:create-expert-profile', kwargs={'pk': self.object.expert_profile.pk})


create_expert = CreateExpert.as_view()


class CreateExpertProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ExpertProfile
    fields = ['bio',
              'profile_picture',
              'areas_expertise',
              'affiliation',
              'website',
              'twitter_profile',
              'linkedin_profile',
              ]
    template_name = 'moderation/create_expert_profile.html'
    success_message = _('Expert profile created successfully')
    success_url = reverse_lazy('moderation:handling')
    context_object_name = 'profile'


create_expert_profile = CreateExpertProfile.as_view()

klimaat_helpdesk/qa/views.py
from logging import getLogger

from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse
from django.utils.timezone import now

from django.views.generic import FormView, ListView, UpdateView, DetailView
from django.views.generic.base import View, TemplateView

from klimaat_helpdesk.qa.forms import AddNewQuestion, AskQuestion
from klimaat_helpdesk.qa.models import Question, Answer, Review, Category, TemporaryQuestion
from klimaat_helpdesk.users import HANDLER, EXPERT, REVIEWER

User = get_user_model()

logger = getLogger(__name__)


class HomePage(TemplateView):
    template_name = 'qa/home_page.html'

    def get_context_data(self, **kwargs):
        latest_questions = Question.objects.more_recent(10)
        categories = Category.objects.all()
        expert_profile = None
        context = super(HomePage, self).get_context_data(**kwargs)
        context.update({
            'latest_questions': latest_questions,
            'categories': categories,
            'expert_profile': expert_profile,
        })
        return context

home_page = HomePage.as_view()


class NewQuestion(FormView):
    form_class = AskQuestion
    template_name = 'qa/new_question.html'
    success_url = reverse_lazy('questions:new-question-thanks')

    def form_valid(self, form):
        TemporaryQuestion.objects.create(
            question=form.cleaned_data['question'],
            asked_by=form.cleaned_data.get('asked_by', None),
            asked_by_ip=self.request.META.get('REMOTE_ADDR')
        )
        return super(NewQuestion, self).form_valid(form)


new_question = NewQuestion.as_view()


class EditorHomeView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'qa/editor_home.html'


editor_home = EditorHomeView.as_view()


class HandlerHomeView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'qa/handler_home.html'


handler_home = HandlerHomeView.as_view()


class AssignHandlerView(UpdateView):
    model = Question
    fields = ['handler', ]
    template_name = 'qa/assign_handler.html'
    success_url = reverse_lazy('questions:editor-home')
    context_object_name = 'question'

    def get_form(self, *args, **kwargs):
        form = super(AssignHandlerView, self).get_form(*args, **kwargs)
        form.fields['handler'].queryset = User.objects.filter(role__gte=HANDLER)
        return form

    def form_valid(self, form):
        self.object.date_assigned_handler = now()
        self.object.save()
        return super(AssignHandlerView, self).form_valid(form)


assign_handler = AssignHandlerView.as_view()


class AssignExpert(UpdateView):
    model = Question
    fields = ['expert', ]
    template_name = 'qa/assign_expert.html'
    success_url = reverse_lazy('questions:handler-home')

    def get_form(self, *args, **kwargs):
        form = super(AssignExpert, self).get_form(*args, **kwargs)
        form.fields['expert'].queryset = User.objects.filter(role__gte=EXPERT)
        return form

    def form_valid(self, form):
        self.object.date_assigned_expert = now()
        self.object.save()
        Answer.objects.create(
            question=self.object,
            author=form.cleaned_data['expert']
        )

        return super(AssignExpert, self).form_valid(form)


assign_expert = AssignExpert.as_view()


class AssignReviewer(UpdateView):
    model = Question
    fields = ['reviewer', ]
    template_name = 'qa/assign_reviewer.html'
    success_url = reverse_lazy('questions:handler-home')

    def get_form(self, *args, **kwargs):
        form = super(AssignReviewer, self).get_form(*args, **kwargs)
        form.fields['reviewer'].queryset = User.objects.filter(role__gte=REVIEWER)
        return form

    def form_valid(self, form):
        self.object.date_assigned_reviewer = now()
        self.object.save()
        Review.objects.create(
            question=self.object,
            reviewer=form.cleaned_data['reviewer']
        )

        return super(AssignReviewer, self).form_valid(form)


assign_reviewer = AssignReviewer.as_view()


class CreateAnswer(UpdateView):
    model = Answer
    fields = ['answer', ]
    context_object_name = 'answer'
    template_name = 'qa/create_answer.html'
    success_url = '/'

    def form_valid(self, form):
        self.object.date_submitted = now()
        self.object.save()
        return super(CreateAnswer, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('questions:question-details', args=[self.object.question.pk])


create_answer = CreateAnswer.as_view()


class ReviewAnswer(UpdateView):
    model = Review
    fields = ['remarks', ]
    context_object_name = 'review'
    template_name = 'qa/create_review.html'
    success_url = '/'

    def form_valid(self, form):
        self.object.date_submitted = now()
        self.object.save()
        return super(ReviewAnswer, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('questions:question-details', args=[self.object.question.pk])


review_answer = ReviewAnswer.as_view()


class QuestionDetails(DetailView):
    model = Question
    template_name = 'qa/question_details.html'
    context_object_name = 'question'


question_details = QuestionDetails.as_view()

klimaat_helpdesk/templates/moderation/approve_question.html
{% extends 'moderation/base.html' %}
{% load static i18n %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "Approve Question" %}</h2>
          <p>{% blocktrans %}Review the question below. If you believe it is worth it, approve it. In the next step you
            will need to select a handler for the question
          {% endblocktrans %}</p>
          <article class="media boxed">
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>{{ question.question }}</strong>
                  <br>
                  {% if question.asked_by %}Asked by: {{ question.asked_by }} {% endif %}
                </p>
              </div>
            </div>
          </article>
          <form method="post" class="form boxed">
            {% csrf_token %}
            <button class="button is-primary">{% trans "Approve" %}</button>
          </form>
        </main>
        <aside class="column is-one-quarter sidebar">
          <div class="boxed sidebar-box">
            <h4 class="title section-title">{% trans "Tools" %}</h4>
            <ul class="sidebar-categories">
              <li><a>{% trans "Check Answer Progress" %}</a></li>
              <li><a>{% trans "Create Expert" %}</a></li>
              <li><a>{% trans "View Stats" %}</a></li>
            </ul>
          </div>
        </aside>
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/assign_expert.html
{% extends 'moderation/base.html' %}
{% load static i18n bulma_tags %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "Assign an Expert" %}</h2>
          <p>{% blocktrans %}Select who is going to answer the question. The expert will get an automatic e-mail with
            information on how to proceed.
          {% endblocktrans %}</p>
          <article class="media boxed">
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>{{ question.question }}</strong>
                  <br>
                  {% if question.asked_by %}Asked by: {{ question.asked_by }} {% endif %}
                </p>
              </div>
            </div>
          </article>
          <form method="post" class="form boxed">
            {% csrf_token %}
            {{ form|bulma }}
            <button class="button is-primary">{% trans "Assign Expert" %}</button>
          </form>
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/assign_handler.html
{% extends 'moderation/base.html' %}
{% load static i18n bulma_tags %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "Assign a Handler" %}</h2>
          <p>{% blocktrans %}Select who is going to handle the workflow of question.
          {% endblocktrans %}</p>
          <article class="media boxed">
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>{{ question.question }}</strong>
                  <br>
                  {% if question.asked_by %}Asked by: {{ question.asked_by }} {% endif %}
                </p>
              </div>
            </div>
          </article>
          <form method="post" class="form boxed">
            {% csrf_token %}
            {{ form|bulma }}
            <button class="button is-primary">{% trans "Approve" %}</button>
          </form>
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/base.html
{% extends "base.html" %}

klimaat_helpdesk/templates/moderation/create_expert.html
{% extends 'moderation/base.html' %}
{% load static i18n bulma_tags %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "Create an Expert" %}</h2>
          <p>{% blocktrans %}First create a user, then you will be able to add a profile.
          {% endblocktrans %}</p>
          <form method="post" class="form boxed">
            {% csrf_token %}
            {{ form|bulma }}
            <button class="button is-primary">{% trans "Create Expert" %}</button>
          </form>
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/create_expert_profile.html
{% extends 'moderation/base.html' %}
{% load static i18n bulma_tags %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% blocktrans with user=user.name %}Create a Profile Expert {{ user }}{% endblocktrans %}</h2>
          <p>{% blocktrans %}Add the fields you think are necessary. Nothing is really mandatory and the expert can
            update them later.
          {% endblocktrans %}</p>
          <form method="post" class="form boxed">
            {% csrf_token %}
            {{ form|bulma }}
            <button class="button is-primary">{% trans "Create Expert" %}</button>
          </form>
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/handling.html
{% extends 'moderation/base.html' %}
{% load static i18n %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "List of questions to handle" %}</h2>
          {% if not questions %}
            <p>{% trans "You are currently not handling any questions." %}</p>
          {% endif %}
          {% for question in questions %}
            <article class="media boxed">
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong>{{ question.question }}</strong>
                    <br>
                    {% if question.asked_by %}Asked by: {{ question.asked_by }} {% endif %}
                  </p>
                  <p>Current status: {{ question.current_status }}</p>
                </div>
                <nav class="level is-mobile">
                  <div class="level-left">
                    <a class="level-item" aria-label="Assign Expert" href="{% url 'moderation:assign-expert' question.pk %}">
                      <span class="icon is-small">
                        <i class="fas fa-chalkboard-teacher" title="Assign Expert"></i>
                      </span>
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          {% endfor %}
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/new_questions.html
{% extends 'moderation/base.html' %}
{% load static i18n %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "List of questions to moderate" %}</h2>
        {% if not questions %}
          <div class="container-fluid">
          <h1 class="subtitle">{% blocktrans %}There are no questions to moderate. Hooray!{% endblocktrans %}</h1>
          <p>{% blocktrans %}Since there are no questions to moderate, you can check whether you have assigned questions
          to handle{% endblocktrans %}</p>
          </div>
        {% endif %}
          {% for question in questions %}
            <article class="media boxed">
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong>{{ question.question }}</strong>
                    <br>
                    {% if question.asked_by %}Asked by: {{ question.asked_by }} {% endif %}

                  </p>
                </div>
                <nav class="level is-mobile">
                  <div class="level-left">
                    <a class="level-item" aria-label="approve" href="{% url 'moderation:approve' question.pk %}">
            <span class="icon is-small">
              <i class="far fa-thumbs-up" title="{% trans "Approve" %}"></i>
            </span>
                    </a>
                    <a class="level-item" aria-label="reject" href="{% url 'moderation:reject' question.pk %}">
            <span class="icon is-small">
              <i class="far fa-thumbs-down" title="{% trans "Reject" %}"></i>
            </span>
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          {% endfor %}
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}

klimaat_helpdesk/templates/moderation/reject_question.html
{% extends 'moderation/base.html' %}
{% load static i18n bulma_tags %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="columns">
        <main class="column">
          <h2 class="title">{% trans "Reject Question" %}</h2>
          <p>{% blocktrans %}Review the question below. If you believe this question is not appropriate for the website,
            you can reject it. Please write a short description of why the question was rejected, for example, it is a
            duplicate, doesn't meet the standards, etc. If the person who submitted the question supplied an e-mail,
            they will be notified about the decision.
          {% endblocktrans %}</p>
          <article class="media boxed">
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>{{ question.question }}</strong>
                  <br>
                  {% if question.asked_by %}Asked by: {{ question.asked_by }} {% endif %}
                </p>
              </div>
            </div>
          </article>
          <form method="post" class="form boxed">
            {% csrf_token %}
            {{ form|bulma }}
            <button class="button is-primary">{% trans "Reject" %}</button>
          </form>
        </main>
        {% include 'moderation/includes/aside.html' %}
      </div>
    </div>
  </section>
{% endblock %}